### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by BrianMwas** [VirgilSecurity/virgil-sdk-go#62]
I am facing the error below when trying to build the app. Not sure why this is happening am running on an apple silicon machine which should not be a problem.
`skipping incompatible /go/pkg/mod/github.com/!virgil!security/virgil-sdk-go/v6@v6.0.15/crypto/wrapper/foundation/../pkg/linux_amd64/lib/libfalcon.a when searching for -lfalcon
#0 119.5 /usr/bin/ld: cannot find -lfalcon`

**Comment by BrianMwas** [comment]
Are there any prerequisite steps to follow to run it from an image because this has been a pain for a couple of days

**Comment by Scratch-net** [comment]
Apple silicon is not supported, sorry. SDK uses C libraries build for linux only

**Comment by Scratch-net** [comment]
You can try [building](https://github.com/VirgilSecurity/virgil-sdk-go/tree/9a68a037437dfca3135d2412bc2750803907f9e5/crypto) virgil-crypto-c yourself and put it into pkg folder, adding platform specific lines to [this](https://github.com/VirgilSecurity/virgil-sdk-go/blob/9a68a037437dfca3135d2412bc2750803907f9e5/crypto/wrapper/foundation/platform.go) file
